version: "3.9"
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    volumes:
      - /pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    depends_on:
      - db
    build: .
    ports:
      - "8001:8001"
